routes/web.php
<?php

// guest routes
Auth::routes(['verify' => true]);

Route::get('/register/', ['uses' => '\App\Http\Controllers\Auth\RegisterController@showRegistrationForm']);
Route::get('/register/{role}', ['uses' => '\App\Http\Controllers\Auth\RegisterController@index']);
Route::post('/register/{role}', ['uses' => '\App\Http\Controllers\Auth\RegisterController@register']);

Route::group(['namespace' => 'App'], function () {
    Route::get('/', ['uses' => 'HomeController@index', 'as' => 'app.home.index']);
    Route::get('/contact-us', ['uses' => 'HomeController@contact', 'as' => 'app.home.contact']);
    Route::get('/about', ['uses' => 'HomeController@about', 'as' => 'app.home.about']);
    Route::get('/terms', ['uses' => 'HomeController@term', 'as' => 'app.home.term']);
    Route::get('/privacy', ['uses' => 'HomeController@privacy', 'as' => 'app.home.privacy']);
});

Route::group(['middleware' => ['role:admin'], 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'admin.dashboard.index']);
    Route::post('/user/list', ['uses' => 'UserController@list', 'as' => 'admin']);
    Route::resource('/user', 'UserController', ['as' => 'admin']);
    Route::get('/user/{user}/orders', ['uses' => 'UserController@orders', 'as' => 'admin.user.order']);
    Route::get('/user/{user}/balance', ['uses' => 'UserController@balances', 'as' => 'admin.user.balance']);
    Route::get('/user/{user}/shipment', ['uses' => 'UserController@shipments', 'as' => 'admin.user.shipment']);
    Route::get('/user/{user}/address', ['uses' => 'UserController@addresses', 'as' => 'admin.user.address']);

    Route::resource('/order', 'OrderController', ['as' => 'admin']);
    Route::post('/order/getOrdersByUser', ['uses' => 'OrderController@getOrdersByUser', 'as' => 'admin.order.user']);
    Route::resource('/shipment', 'ShipmentController', ['as' => 'admin']);
    Route::resource('/shipment.status', 'ShipmentStatusController', ['as' => 'admin']);
    Route::resource('/shipment.service', 'ShipmentServiceController', ['as' => 'admin']);
    Route::resource('/shipment-schedule', 'ShipmentScheduleController', ['as' => 'admin']);
    Route::resource('/shipment-provider', 'ShipmentProviderController', ['as' => 'admin']);

    Route::resource('/bank', 'BankController', ['as' => 'admin']);
    Route::post('/bank/getOrdersByUser', ['uses' => 'BankController@getBanksByUser', 'as' => 'admin.bank.user']);

    Route::resource('/bank-type', 'BankTypeController', ['as' => 'admin']);
    Route::resource('/coupon', 'CouponController', ['as' => 'admin']);
    Route::resource('/package', 'PackageController', ['as' => 'admin']);
    Route::resource('/report', 'ReportController', ['as' => 'admin']);
    Route::resource('/transfer', 'TransferController', ['as' => 'admin']);
    Route::resource('/address', 'AddressController', ['as' => 'admin']);
    Route::resource('/app-setting', 'AppSettingController', ['as' => 'admin']);
    Route::resource('/slider', 'SliderController', ['as' => 'admin']);
});

Route::group(['namespace' => 'App', 'middleware' => ['role:admin|trader|customer', 'verified', 'packageIsSelected']], function () {
    Route::get('/user/setting/', ['uses' => 'UserController@setting', 'as' => 'app.user.setting']);
    Route::get('/user/transfer-period/', ['uses' => 'UserController@duration', 'as' => 'app.user.duration']);
    Route::post('/user/transfer-period/', ['uses' => 'UserController@post_duration', 'as' => 'app.user.duration']);
    Route::resource('/user', 'UserController', ['as' => 'app']);
    
    Route::resource('/notification', 'NotificationController', ['as' => 'app']);


    Route::get('/shipment/filter/{addressType?}/{shipmentStatus?}', ['uses' => 'ShipmentController@filter', 'as' => 'app.shipment.track']);
    Route::resource('/shipment', 'ShipmentController', ['as' => 'app']);
    Route::get('/shipment-track/', ['uses' => 'ShipmentController@get_track', 'as' => 'app.shipment.track']);
    Route::post('/shipment-track/', ['uses' => 'ShipmentController@post_track', 'as' => 'app.shipment.track']);

    Route::get('/order/confirm-order',  ['uses' => 'OrderController@get_confirm', 'as' => 'app.order.confirm']);
    Route::post('/order/confirm-order',  ['uses' => 'OrderController@post_confirm', 'as' => 'app.order.confirm']);
    Route::resource('/order', 'OrderController', ['as' => 'app']);

    Route::resource('/coupon', 'CouponController', ['as' => 'app']);
    Route::resource('/package', 'PackageController', ['as' => 'app']);
    Route::resource('/report', 'ReportController', ['as' => 'app']);
    Route::resource('/transfer', 'TransferController', ['as' => 'app']);
    Route::resource('/address', 'AddressController', ['as' => 'app']);
    Route::get('/address-list/{address_type}', ['uses' => 'AddressController@list_by_type', 'as' => 'app.address.list']);

    Route::resource('/bank', 'BankController', ['as' => 'app']);
});

app/User.php
<?php

namespace App;

class User extends Models\User {
    //leave this empty
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use App\Models\Order;
use App\Models\Package;
use Spatie\Permission\Models\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    public function list()
    {
        $users = User::latest()->get();

        return response()->json(['data' => $users]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::latest()->paginate(15);

        return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::pluck('display_name', 'id');
        $packages = Package::pluck('name', 'id');

        return view('admin.user.create', compact('roles', 'packages'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, 
            ['email' => 'email|unique:users']
        );

        $user = User::create($request->except(['role_id']));
        $user->update(['policies' => \App\Models\Package::find($request->package_id)->policy_number]);
        
        $user->assignRole($request->role_id);
        
        return redirect(route('admin.user.index'))->with('message', 'تم حفظ المعلومات بنجاح!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $pendingOrders = Order::where('user_id', $user->id)->whereIn('order_status_id', [1,2])->count();
        $pendingTransfer = \App\Models\Balance::where('user_id', $user->id)->first()->balance;

        return view('admin.user.show', compact('user', 'pendingOrders','pendingTransfer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::pluck('display_name', 'id');
        $packages = Package::pluck('name', 'id');

        return view('admin.user.edit', compact('user', 'roles', 'packages'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, 
            ['email' => 'email|unique:users,email,'.$user->id]
        );

        $user->update($request->except(['role_id', 'password']));

        if(! is_null($user->password))
        {
            $user->password = bcrypt($request->password);
            $user->save();
        }

        if($request->email_verified_at == 0)
        {
            $user->email_verified_at = \Carbon\Carbon::now();
            $user->save();
        }
        else if($request->email_verified_at == 1)
        {
            $user->email_verified_at = null;
            $user->save();
        }
        
        $user->syncRoles($request->role_id);
        
        return redirect(route('admin.user.index'))->with('message', 'تم حفظ المعلومات بنجاح!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        
        return redirect(route('admin.user.index'))->with('message', 'تم حذف المعلومات بنجاح!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function orders(User $user)
    {
        return view('admin.user.order', compact('user'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function addresses(User $user)
    {
        return view('admin.user.address', compact('user'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function shipments(User $user)
    {
        return view('admin.user.shipment', compact('user'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function balances(User $user)
    {
        // قيمة بضاعة لم تسلم
        $pendingOrders = \App\Models\Shipment::whereHas('order', function($query) use ($user){
            return $query->whereIn('order_status_id', [1,2])->where('user_id', $user->id);
        })->get()->sum('item_cost');

        // مبالغ في انتظار التحويل
        $pendingTransfer = \App\Models\Balance::where('user_id', $user->id)->first()->balance;

        return view('admin.user.balance', compact('user', 'pendingOrders', 'pendingTransfer'));
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\User;
use Spatie\Permission\Models\Role;
use App\Models\TransferDuration;
use App\Models\Package;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $users = User::orderBy('id', 'desc')->get();

        // return view('app.user.show', auth()->user(), compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $roles = Role::pluck('display_name', 'id');

        // return view('app.user.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, 
            ['email' => 'email|unique:users']
        );

        $user = User::create($request->except(['role_id']));
        
        $user->assignRole($request->role_id);
        
        return redirect(route('app.user.show', auth()->user()))->with('message', 'تم حفظ المعلومات بنجاح!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('app.user.show', auth()->user(), compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::pluck('display_name', 'id');

        return view('app.user.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, 
            ['email' => 'email|unique:users,email,'.$user->id]
        );

        $user->update($request->except(['password']));

        if(! is_null($request->password))
        {
            $user->password = bcrypt($request->password);
            $user->save();
        }
        
        return redirect(route('app.user.show', auth()->user()))->with('message', 'تم حفظ المعلومات بنجاح!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        
        return redirect(route('app.user.show', auth()->user()))->with('message', 'تم حذف المعلومات بنجاح!');
    }

    public function duration()
    {
        $durations = TransferDuration::pluck('name', 'id');

        return view('app.transfer.duration', compact('durations'));
    }

    public function post_duration(Request $request)
    {
        $duration = TransferDuration::findOrFail($request->transfer_duration_id);
        auth()->user()->update(['transfer_duration_id' => $duration->id]);

        return redirect(route('app.user.show', auth()->user(), auth()->user()))->with('message', 'تم تحديث بياناتك بنجاح!');
    }

    public function setting()
    {
        $user = auth()->user();
        $packages = Package::pluck('name', 'id');

        return view('app.user.setting', compact('user', 'packages'));
    }
}

app/Http/Controllers/App/UserController.php
<?php

namespace App\Http\Controllers\App;

use App\Models\User;
use Spatie\Permission\Models\Role;
use App\Models\TransferDuration;
use App\Models\Package;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $users = User::orderBy('id', 'desc')->get();

        // return view('app.user.show', auth()->user(), compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $roles = Role::pluck('display_name', 'id');

        // return view('app.user.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, 
            ['email' => 'email|unique:users']
        );

        $user = User::create($request->except(['role_id']));
        
        $user->assignRole($request->role_id);
        
        return redirect(route('app.user.show', auth()->user()))->with('message', 'تم حفظ المعلومات بنجاح!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('app.user.show', auth()->user(), compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::pluck('display_name', 'id');

        return view('app.user.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, 
            ['email' => 'email|unique:users,email,'.$user->id]
        );

        $user->update($request->except(['password']));

        if(! is_null($request->password))
        {
            $user->password = bcrypt($request->password);
            $user->save();
        }
        
        return redirect(route('app.user.show', auth()->user()))->with('message', 'تم حفظ المعلومات بنجاح!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        
        return redirect(route('app.user.show', auth()->user()))->with('message', 'تم حذف المعلومات بنجاح!');
    }

    public function duration()
    {
        $durations = TransferDuration::pluck('name', 'id');

        return view('app.transfer.duration', compact('durations'));
    }

    public function post_duration(Request $request)
    {
        $duration = TransferDuration::findOrFail($request->transfer_duration_id);
        auth()->user()->update(['transfer_duration_id' => $duration->id]);

        return redirect(route('app.user.show', auth()->user(), auth()->user()))->with('message', 'تم تحديث بياناتك بنجاح!');
    }

    public function setting()
    {
        $user = auth()->user();
        $packages = Package::pluck('name', 'id');

        return view('app.user.setting', compact('user', 'packages'));
    }
}

resources/views/app/user/notification.blade.php
@extends('layouts.app')
@section('title')
التنبيهات
@endsection
@section('content')
<div class="account ">
    <div class="container ">
        <div class="row">
			@include('partials.app.account_sidebar')
			<div class="col-md-9  text-center font-weight-bold">
                <div class="address_recived text-center">
                    <h3 class="color2">
                   التنبيهات
                </h3>

                    <hr class="hr">
                    <div class="row">
                    @if($notifications->count() == 0)
                        لا يوجد تنبيهات في الوقت الحالي.
                    @else
                    @foreach($notifications as $notification)
                    <div class="col-12 color2 box ">
                        <div class="float-left">
                            <span>{{ $notification->data['title'] }}</span>
                        </div>
                        <div class=" float-right">
                            <span>{{ $notification->data['text'] }}</span>
                        </div>
                    </div>
                    @endforeach
                    @endif
                    </div>
                    <br>
                </div></div>

            </div>
		</div>
	</div>
</div>
@endsection

resources/views/app/user/setting.blade.php
@extends('layouts.app')
@section('title')
إعدادات الحساب
@endsection
@section('content')
<div class="account ">
    <div class="container ">
        <div class="row">
			@include('partials.app.account_sidebar')
			<div class="col-md-9  text-center"><div class="addadress">
            <h3 class="color2">إعدادات الحساب</h3>
            <hr class="hr">

            {!! Form::model($user, ['route' => ['app.user.update', $user]]) !!}
            {{ method_field('PATCH') }}
                <div class="form-group row">
                    <label for="inputPassword" class="col-5 col-lg-2 col-sm-3 col-form-label">البريد اﻹلكتروني</label>
                    <div class="col-7 col-lg-9 col-sm-8">
                    {!! Form::text('email', null, ['class' => 'form-control boxofinput']) !!}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputPassword" class="col-4 col-lg-2 col-sm-3 col-form-label">الاسم</label>
                    <div class="col-7 col-lg-9 col-sm-8">
                    {!! Form::text('name', null, ['class' => 'form-control boxofinput']) !!}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputPassword" class="col-4 col-lg-2 col-sm-3 col-form-label">رقم الجوال</label>
                    <div class="col-7 col-lg-9 col-sm-8">
                    {!! Form::text('phone', null, ['class' => 'form-control boxofinput']) !!}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputPassword" class="col-4 col-lg-2 col-sm-3 col-form-label">المدينة</label>
                    <div class="col-7 col-lg-9 col-sm-8">
                    {!! Form::text('city', null, ['class' => 'form-control boxofinput']) !!}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputPassword" class="col-4 col-lg-2 col-sm-3 col-form-label">العنوان</label>
                    <div class="col-7 col-lg-9 col-sm-8">
                    {!! Form::text('address', null, ['class' => 'form-control boxofinput']) !!}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputPassword" class="col-4 col-lg-2 col-sm-3 col-form-label">كلمة المرور</label>
                    <div class="col-7 col-lg-9 col-sm-8">
                    <small>أترك الحقل فارغاًإذا كنت ﻻ تريد تغييره.</small>
                    {!! Form::password('password', ['class' => 'form-control boxofinput']) !!}
                    </div>
                </div>
                @if(auth()->user()->hasRole('trader'))
                <div class="form-group row">
                    <label for="inputPassword" class="col-4 col-lg-2 col-sm-3 col-form-label">إسم الشركة</label>
                    <div class="col-7 col-lg-9 col-sm-8">
                    {!! Form::text('company_name', null, ['class' => 'form-control boxofinput']) !!}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputPassword" class="col-4 col-lg-2 col-sm-3 col-form-label">الموقع اﻹلكتروني</label>
                    <div class="col-7 col-lg-9 col-sm-8">
                    {!! Form::text('website', null, ['class' => 'form-control boxofinput']) !!}
                    </div>
                </div>
                @endif
                <div class="form-group row">
                        <div class=" col-4 col-lg-2 col-sm-3 col-form-label "></div>
                        <div class="col-7 col-lg-9 col-sm-8 row">
                            <div class="col-md-12">
                                <button type="submit" class="form-control btn btn-primary my-1 buttonbox">حفظ المعلومات</button>
                            </div>
                        </div>
                </div>

        </form>


            
        </div>

    </div>
		</div>
	</div>
</div>
@endsection

resources/views/app/user/show.blade.php
@extends('layouts.app')
@section('title')
ملفي الشخصي
@endsection
@section('content')
<div class="account ">
    <div class="container ">
        <div class="row">
			@include('partials.app.account_sidebar')
			<div class="col-md-9  text-center">
				<div class="my_account">
					<div class="row font-weight-bold color2">
						<div class="col-md-4 col-6">
						<a href="{{ route('app.order.create') }}">
							<i class="fas fa-truck rounded-circle"></i>
							<p>طلب جديد</p>
						</a>
						</div>

						<div class="col-md-4 col-6">
						<a href="{{ route('app.order.index') }}">
								<i class="fas fa-truck rounded-circle"></i>
								<p>طلباتي</p>
						</a>
						</div>
						<div class="col-md-4 col-6">
						<a href="{{ route('app.address.index') }}">
								<i class="fas fa-map-marker-alt rounded-circle"></i>
								<p>عناوينى</p>
						</a>
						</div>
						<div class="col-md-4 col-6">
							<a href="{{ route('app.bank.index') }}">
								<i class="fas fa-coins rounded-circle"></i>
								<p>حسابات الحولات البنكية</p>
							</a>
						</div>
						@if(auth()->user()->hasAnyRole('trader'))
						<div class="col-md-4 col-6">
						<a href="{{ route('app.user.duration') }}">
								<i class="far fa-credit-card rounded-circle"></i>
								<p>فتره التحويل البنكى</p>
						</a>
						</div>
						<div class="col-md-4 col-6">
							<a href="{{ route('app.transfer.index') }}">
								<i class="fas fa-chart-line rounded-circle"></i>
								<p>حركات الرصيد</p>
							</a>
						</div>
						<div class="col-md-4 col-6">
						<a href="{{ route('app.transfer.create') }}">
								<i class="far fa-credit-card rounded-circle"></i>
								<p>إيداع رصيد</p>
						</a>
						</div>
						@endif
						<div class="col-md-4 col-6">
						<a href="{{ route('app.coupon.create') }}">
								<i class="fas fa-gift rounded-circle"></i>
								<p>تفعيل قسيمة</p>
						</a>
						</div>
						<div class="col-md-4 col-6">
						<a href="{{ route('app.report.index') }}">
								<i class="fas fa-file rounded-circle"></i>
								<p>التقارير</p>
						</a>
						</div>
						<div class="col-md-4 col-6">
						<a href="{{ route('app.shipment.index') }}">

								<i class="fas fa-cube rounded-circle"></i>
								<p>شحناتى</p>
</a>
						</div>
						<div class="col-md-4 col-12" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('frm-logout').submit();">
								<i class="fas fa-power-off rounded-circle"></i>
								<p>تسجيل خروج</p>
						</div>
        <form id="frm-logout" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
        </form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection