routes/web.php
<?php

// guest routes
Auth::routes(['verify' => true]);

Route::get('/register/', ['uses' => '\App\Http\Controllers\Auth\RegisterController@showRegistrationForm']);
Route::get('/register/{role}', ['uses' => '\App\Http\Controllers\Auth\RegisterController@index']);
Route::post('/register/{role}', ['uses' => '\App\Http\Controllers\Auth\RegisterController@register']);

Route::group(['namespace' => 'App'], function () {
    Route::get('/', ['uses' => 'HomeController@index', 'as' => 'app.home.index']);
    Route::get('/contact-us', ['uses' => 'HomeController@contact', 'as' => 'app.home.contact']);
    Route::get('/about', ['uses' => 'HomeController@about', 'as' => 'app.home.about']);
    Route::get('/terms', ['uses' => 'HomeController@term', 'as' => 'app.home.term']);
    Route::get('/privacy', ['uses' => 'HomeController@privacy', 'as' => 'app.home.privacy']);
});

Route::group(['middleware' => ['role:admin'], 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'admin.dashboard.index']);
    Route::post('/user/list', ['uses' => 'UserController@list', 'as' => 'admin']);
    Route::resource('/user', 'UserController', ['as' => 'admin']);
    Route::get('/user/{user}/orders', ['uses' => 'UserController@orders', 'as' => 'admin.user.order']);
    Route::get('/user/{user}/balance', ['uses' => 'UserController@balances', 'as' => 'admin.user.balance']);
    Route::get('/user/{user}/shipment', ['uses' => 'UserController@shipments', 'as' => 'admin.user.shipment']);
    Route::get('/user/{user}/address', ['uses' => 'UserController@addresses', 'as' => 'admin.user.address']);

    Route::resource('/order', 'OrderController', ['as' => 'admin']);
    Route::post('/order/getOrdersByUser', ['uses' => 'OrderController@getOrdersByUser', 'as' => 'admin.order.user']);
    Route::resource('/shipment', 'ShipmentController', ['as' => 'admin']);
    Route::resource('/shipment.status', 'ShipmentStatusController', ['as' => 'admin']);
    Route::resource('/shipment.service', 'ShipmentServiceController', ['as' => 'admin']);
    Route::resource('/shipment-schedule', 'ShipmentScheduleController', ['as' => 'admin']);
    Route::resource('/shipment-provider', 'ShipmentProviderController', ['as' => 'admin']);

    Route::resource('/bank', 'BankController', ['as' => 'admin']);
    Route::post('/bank/getOrdersByUser', ['uses' => 'BankController@getBanksByUser', 'as' => 'admin.bank.user']);

    Route::resource('/bank-type', 'BankTypeController', ['as' => 'admin']);
    Route::resource('/coupon', 'CouponController', ['as' => 'admin']);
    Route::resource('/package', 'PackageController', ['as' => 'admin']);
    Route::resource('/report', 'ReportController', ['as' => 'admin']);
    Route::resource('/transfer', 'TransferController', ['as' => 'admin']);
    Route::resource('/address', 'AddressController', ['as' => 'admin']);
    Route::resource('/app-setting', 'AppSettingController', ['as' => 'admin']);
    Route::resource('/slider', 'SliderController', ['as' => 'admin']);
});

Route::group(['namespace' => 'App', 'middleware' => ['role:admin|trader|customer', 'verified', 'packageIsSelected']], function () {
    Route::get('/user/setting/', ['uses' => 'UserController@setting', 'as' => 'app.user.setting']);
    Route::get('/user/transfer-period/', ['uses' => 'UserController@duration', 'as' => 'app.user.duration']);
    Route::post('/user/transfer-period/', ['uses' => 'UserController@post_duration', 'as' => 'app.user.duration']);
    Route::resource('/user', 'UserController', ['as' => 'app']);
    
    Route::resource('/notification', 'NotificationController', ['as' => 'app']);


    Route::get('/shipment/filter/{addressType?}/{shipmentStatus?}', ['uses' => 'ShipmentController@filter', 'as' => 'app.shipment.track']);
    Route::resource('/shipment', 'ShipmentController', ['as' => 'app']);
    Route::get('/shipment-track/', ['uses' => 'ShipmentController@get_track', 'as' => 'app.shipment.track']);
    Route::post('/shipment-track/', ['uses' => 'ShipmentController@post_track', 'as' => 'app.shipment.track']);

    Route::get('/order/confirm-order',  ['uses' => 'OrderController@get_confirm', 'as' => 'app.order.confirm']);
    Route::post('/order/confirm-order',  ['uses' => 'OrderController@post_confirm', 'as' => 'app.order.confirm']);
    Route::resource('/order', 'OrderController', ['as' => 'app']);

    Route::resource('/coupon', 'CouponController', ['as' => 'app']);
    Route::resource('/package', 'PackageController', ['as' => 'app']);
    Route::resource('/report', 'ReportController', ['as' => 'app']);
    Route::resource('/transfer', 'TransferController', ['as' => 'app']);
    Route::resource('/address', 'AddressController', ['as' => 'app']);
    Route::get('/address-list/{address_type}', ['uses' => 'AddressController@list_by_type', 'as' => 'app.address.list']);

    Route::resource('/bank', 'BankController', ['as' => 'app']);
});

resources/views/partials/admin/breadcrumbs.blade.php
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item">
                    <a href="{{ route('admin.dashboard.index') }}" class="m-nav__link">
                        <span class="m-nav__link-text">لوحة التحكم</span>
                    </a>
                </li>
                @if(\Request::segment(2) != null && \Request::segment(3) == null)
                <li class="m-nav__separator">></li>
                <li class="m-nav__item">
                    <a href="{{ route('admin.'.Request::segment(2).'.index') }}" class="m-nav__link">
                        <span class="m-nav__link-text">{{ __('general.'.Request::segment(2)) }}</span>
                    </a>
                </li>
                @endif
                @if(\Request::segment(3) != null)
				<li class="m-nav__separator">></li>
                <li class="m-nav__item">
                    <a href="{{ route('admin.'.Request::segment(2).'.index') }}" class="m-nav__link">
                        <span class="m-nav__link-text">{{ __('general.'.Request::segment(2)) }}</span>
                    </a>
                </li>
                @endif
                <li class="m-nav__separator">></li>
                <li class="m-nav__item">
                    <a href="#" class="m-nav__link">
                        <span class="m-nav__link-text--active">@yield('title')</span>
                    </a>
                </li>
			</ul>
        </div>
        <!-- <div>
            <span class="m-subheader__daterange" id="m_dashboard_daterangepicker">
                <span class="m-subheader__daterange-label">
                    <span class="m-subheader__daterange-title"></span>
                    <span class="m-subheader__daterange-date m--font-brand"></span>
                </span>
                <a href="#" class="btn btn-sm btn-brand m-btn m-btn--icon m-btn--icon-only m-btn--custom m-btn--pill">
                    <i class="la la-angle-down"></i>
                </a>
            </span>
        </div> -->
    </div>
</div>

resources/views/partials/admin/footer.blade.php
<footer class="m-grid__item		m-footer ">
	<div class="m-container m-container--fluid m-container--full-height m-page__container">
		<div class="m-stack m-stack--flex-tablet-and-mobile m-stack--ver m-stack--desktop">
			<div class="m-stack__item m-stack__item--left m-stack__item--middle m-stack__item--last">
				<span class="m-footer__copyright">
					جميع الحقوق محفوظة لـ {{ config('app.name') }} {{ date('Y') }}
				</span>
			</div>
			<div class="m-stack__item m-stack__item--right m-stack__item--middle m-stack__item--first">
                <span class="m-footer__copyright">
				    <a href="http://www.bananhost.com" target="_blank" style="color: black; font-weight: bold;">تصميم وإستضافة بنان</a>
				</span>    
			</div>	
		</div>
	</div>
</footer>

resources/views/partials/admin/messages.blade.php
@if ($errors->any())
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <ul class="list-group">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session('message'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    </button>
    <strong>{{ session('message') }}</strong>				  	
</div>
@endif

resources/views/partials/admin/sidebar.blade.php
<!-- BEGIN: Left Aside -->
<button class="m-aside-left-close m-aside-left-close--skin-dark " id="m_aside_left_close_btn"><i class="la la-close"></i></button>
<div id="m_aside_left" class="m-grid__item m-aside-left m-aside-left--skin-dark ">
    <!-- BEGIN: Aside Menu -->
    <div id="m_ver_menu" class="m-aside-menu m-aside-menu--skin-dark m-aside-menu--submenu-skin-dark m-aside-menu--dropdown " m-menu-vertical="1" m-menu-dropdown="1" m-menu-scrollable="0" m-menu-dropdown-timeout="500" style="position: relative;">
        <ul class="m-menu__nav m-menu__nav--dropdown-submenu-arrow ">
            <li class="m-menu__item {{ \Request::segment(2) == null ? 'm-menu__item--active' : '' }}" aria-haspopup="true" >
                <a href="{{ route('admin.dashboard.index') }}" class="m-menu__link ">
                    <i class="m-menu__link-icon fa fa-tachometer-alt"></i>
                    <span class="m-menu__link-title">
                        <span class="m-menu__link-wrap">
                            <span class="m-menu__link-text">الصفحة الرئيسية</span> 
                        </span>
                    </span>
                </a>
            </li>
            <li class="m-menu__item m-menu__item--submenu {{ \Request::segment(2) == 'user' ? 'm-menu__item--active' : '' }}" aria-haspopup="true" m-menu-submenu-toggle="hover">
                <a href="javascript:;" class="m-menu__link m-menu__toggle"><i class="m-menu__link-icon fa fa-users"></i><span class="m-menu__link-text">المستخدمين</span><i class="m-menu__ver-arrow la la-angle-right"></i></a>
                <div class="m-menu__submenu ">
                    <span class="m-menu__arrow"></span>
                    <ul class="m-menu__subnav">
                        <li class="m-menu__item " aria-haspopup="true" >
                            <a href="{{ route('admin.user.index') }}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i>
                                <span class="m-menu__link-text">عرض المستخدمين</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="m-menu__item m-menu__item--submenu {{ \Request::segment(2) == 'order' ? 'm-menu__item--active' : '' }}" aria-haspopup="true" m-menu-submenu-toggle="hover">
                <a href="javascript:;" class="m-menu__link m-menu__toggle"><i class="m-menu__link-icon fa fa-copy"></i><span class="m-menu__link-text">الطلبات</span><i class="m-menu__ver-arrow la la-angle-right"></i></a>
                <div class="m-menu__submenu ">
                    <span class="m-menu__arrow"></span>
                    <ul class="m-menu__subnav">
                        <li class="m-menu__item " aria-haspopup="true" >
                            <a href="{{ route('admin.order.index') }}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i>
                                <span class="m-menu__link-text">عرض الطلبات</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="m-menu__item m-menu__item--submenu {{ \Request::segment(2) == 'shipment' ? 'm-menu__item--active' : '' }}" aria-haspopup="true" m-menu-submenu-toggle="hover">
                <a href="javascript:;" class="m-menu__link m-menu__toggle"><i class="m-menu__link-icon fa fa-truck"></i><span class="m-menu__link-text">الشحن</span><i class="m-menu__ver-arrow la la-angle-right"></i></a>
                <div class="m-menu__submenu ">
                    <span class="m-menu__arrow"></span>
                    <ul class="m-menu__subnav">
                        <li class="m-menu__item " aria-haspopup="true" >
                            <a href="{{ route('admin.shipment.index') }}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i>
                                <span class="m-menu__link-text">عرض طلبات الشحن</span>
                            </a>
                        </li>
                        <!-- <li class="m-menu__item " aria-haspopup="true" >
                            <a href="" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i>
                                <span class="m-menu__link-text">حالات الشحن</span>
                            </a>
                        </li> -->
                        <li class="m-menu__item " aria-haspopup="true" >
                            <a href="{{ route('admin.shipment-schedule.index') }}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i>
                                <span class="m-menu__link-text">مواعيد الشحن</span>
                            </a>
                        </li>
                        <li class="m-menu__item " aria-haspopup="true" >
                            <a href="{{ route('admin.shipment-provider.index') }}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i>
                                <span class="m-menu__link-text">مزودي خدمات الشحن</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="m-menu__item m-menu__item--submenu {{ \Request::segment(2) == 'transfer' ? 'm-menu__item--active' : '' }}" aria-haspopup="true" m-menu-submenu-toggle="hover">
                <a href="javascript:;" class="m-menu__link m-menu__toggle"><i class="m-menu__link-icon fa fa-exchange-alt"></i><span class="m-menu__link-text">الحوالات</span><i class="m-menu__ver-arrow la la-angle-right"></i></a>
                <div class="m-menu__submenu ">
                    <span class="m-menu__arrow"></span>
                    <ul class="m-menu__subnav">
                        <li class="m-menu__item " aria-haspopup="true" >
                            <a href="{{ route('admin.transfer.index') }}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i>
                                <span class="m-menu__link-text">عرض الحوالات</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="m-menu__item m-menu__item--submenu {{ \Request::segment(2) == 'bank' ? 'm-menu__item--active' : '' }}" aria-haspopup="true" m-menu-submenu-toggle="hover">
                <a href="javascript:;" class="m-menu__link m-menu__toggle"><i class="m-menu__link-icon fa fa-money-check-alt"></i><span class="m-menu__link-text">البنوك</span><i class="m-menu__ver-arrow la la-angle-right"></i></a>
                <div class="m-menu__submenu ">
                    <span class="m-menu__arrow"></span>
                    <ul class="m-menu__subnav">
                        <li class="m-menu__item " aria-haspopup="true" >
                            <a href="{{ route('admin.bank.index') }}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i>
                                <span class="m-menu__link-text">عرض البنوك</span>
                            </a>
                        </li>
                        <li class="m-menu__item " aria-haspopup="true" >
                            <a href="{{ route('admin.bank-type.index') }}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i>
                                <span class="m-menu__link-text">مزودي الخدمات البنكية</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="m-menu__item m-menu__item--submenu {{ \Request::segment(2) == 'coupon' ? 'm-menu__item--active' : '' }}" aria-haspopup="true" m-menu-submenu-toggle="hover">
                <a href="javascript:;" class="m-menu__link m-menu__toggle"><i class="m-menu__link-icon fa fa-minus"></i><span class="m-menu__link-text">الكوبونات</span><i class="m-menu__ver-arrow la la-angle-right"></i></a>
                <div class="m-menu__submenu ">
                    <span class="m-menu__arrow"></span>
                    <ul class="m-menu__subnav">
                        <li class="m-menu__item " aria-haspopup="true" >
                            <a href="{{ route('admin.coupon.index') }}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i>
                                <span class="m-menu__link-text">عرض الكوبونات</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="m-menu__item m-menu__item--submenu {{ \Request::segment(2) == 'package' ? 'm-menu__item--active' : '' }}" aria-haspopup="true" m-menu-submenu-toggle="hover">
                <a href="javascript:;" class="m-menu__link m-menu__toggle"><i class="m-menu__link-icon fa fa-cubes"></i><span class="m-menu__link-text">الباقات</span><i class="m-menu__ver-arrow la la-angle-right"></i></a>
                <div class="m-menu__submenu ">
                    <span class="m-menu__arrow"></span>
                    <ul class="m-menu__subnav">
                        <li class="m-menu__item " aria-haspopup="true" >
                            <a href="{{ route('admin.package.index') }}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i>
                                <span class="m-menu__link-text">عرض الباقات</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="m-menu__item m-menu__item--submenu {{ \Request::segment(2) == 'report' ? 'm-menu__item--active' : '' }}" aria-haspopup="true" m-menu-submenu-toggle="hover">
                <a href="javascript:;" class="m-menu__link m-menu__toggle"><i class="m-menu__link-icon fa fa-file-alt"></i><span class="m-menu__link-text">التقارير</span><i class="m-menu__ver-arrow la la-angle-right"></i></a>
                <div class="m-menu__submenu ">
                    <span class="m-menu__arrow"></span>
                    <ul class="m-menu__subnav">
                        <li class="m-menu__item " aria-haspopup="true" >
                            <a href="{{ route('admin.report.index') }}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i>
                                <span class="m-menu__link-text">عرض التقارير</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="m-menu__item m-menu__item--submenu {{ \Request::segment(2) == 'slider' ? 'm-menu__item--active' : '' }}" aria-haspopup="true" m-menu-submenu-toggle="hover">
                <a href="javascript:;" class="m-menu__link m-menu__toggle"><i class="m-menu__link-icon fa fa-address-card"></i><span class="m-menu__link-text">السلايدات</span><i class="m-menu__ver-arrow la la-angle-right"></i></a>
                <div class="m-menu__submenu ">
                    <span class="m-menu__arrow"></span>
                    <ul class="m-menu__subnav">
                        <li class="m-menu__item " aria-haspopup="true" >
                            <a href="{{ route('admin.slider.index') }}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i>
                                <span class="m-menu__link-text">عرض السلايدات</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="m-menu__item m-menu__item--submenu {{ \Request::segment(2) == 'app-setting' ? 'm-menu__item--active' : '' }}" aria-haspopup="true" m-menu-submenu-toggle="hover">
                <a href="javascript:;" class="m-menu__link m-menu__toggle"><i class="m-menu__link-icon fa fa-file-alt"></i><span class="m-menu__link-text">إعدادات النظام</span><i class="m-menu__ver-arrow la la-angle-right"></i></a>
                <div class="m-menu__submenu ">
                    <span class="m-menu__arrow"></span>
                    <ul class="m-menu__subnav">
                        <li class="m-menu__item " aria-haspopup="true" >
                            <a href="{{ route('admin.app-setting.index') }}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i>
                                <span class="m-menu__link-text">عرض اﻹعدادات</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
    <!-- END: Aside Menu -->
</div>
<!-- END: Left Aside -->