routes/web.php
<?php

// guest routes
Auth::routes(['verify' => true]);

Route::get('/register/', ['uses' => '\App\Http\Controllers\Auth\RegisterController@showRegistrationForm']);
Route::get('/register/{role}', ['uses' => '\App\Http\Controllers\Auth\RegisterController@index']);
Route::post('/register/{role}', ['uses' => '\App\Http\Controllers\Auth\RegisterController@register']);

Route::group(['namespace' => 'App'], function () {
    Route::get('/', ['uses' => 'HomeController@index', 'as' => 'app.home.index']);
    Route::get('/contact-us', ['uses' => 'HomeController@contact', 'as' => 'app.home.contact']);
    Route::get('/about', ['uses' => 'HomeController@about', 'as' => 'app.home.about']);
    Route::get('/terms', ['uses' => 'HomeController@term', 'as' => 'app.home.term']);
    Route::get('/privacy', ['uses' => 'HomeController@privacy', 'as' => 'app.home.privacy']);
});

Route::group(['middleware' => ['role:admin'], 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'admin.dashboard.index']);
    Route::post('/user/list', ['uses' => 'UserController@list', 'as' => 'admin']);
    Route::resource('/user', 'UserController', ['as' => 'admin']);
    Route::get('/user/{user}/orders', ['uses' => 'UserController@orders', 'as' => 'admin.user.order']);
    Route::get('/user/{user}/balance', ['uses' => 'UserController@balances', 'as' => 'admin.user.balance']);
    Route::get('/user/{user}/shipment', ['uses' => 'UserController@shipments', 'as' => 'admin.user.shipment']);
    Route::get('/user/{user}/address', ['uses' => 'UserController@addresses', 'as' => 'admin.user.address']);

    Route::resource('/order', 'OrderController', ['as' => 'admin']);
    Route::post('/order/getOrdersByUser', ['uses' => 'OrderController@getOrdersByUser', 'as' => 'admin.order.user']);
    Route::resource('/shipment', 'ShipmentController', ['as' => 'admin']);
    Route::resource('/shipment.status', 'ShipmentStatusController', ['as' => 'admin']);
    Route::resource('/shipment.service', 'ShipmentServiceController', ['as' => 'admin']);
    Route::resource('/shipment-schedule', 'ShipmentScheduleController', ['as' => 'admin']);
    Route::resource('/shipment-provider', 'ShipmentProviderController', ['as' => 'admin']);

    Route::resource('/bank', 'BankController', ['as' => 'admin']);
    Route::post('/bank/getOrdersByUser', ['uses' => 'BankController@getBanksByUser', 'as' => 'admin.bank.user']);

    Route::resource('/bank-type', 'BankTypeController', ['as' => 'admin']);
    Route::resource('/coupon', 'CouponController', ['as' => 'admin']);
    Route::resource('/package', 'PackageController', ['as' => 'admin']);
    Route::resource('/report', 'ReportController', ['as' => 'admin']);
    Route::resource('/transfer', 'TransferController', ['as' => 'admin']);
    Route::resource('/address', 'AddressController', ['as' => 'admin']);
    Route::resource('/app-setting', 'AppSettingController', ['as' => 'admin']);
    Route::resource('/slider', 'SliderController', ['as' => 'admin']);
});

Route::group(['namespace' => 'App', 'middleware' => ['role:admin|trader|customer', 'verified', 'packageIsSelected']], function () {
    Route::get('/user/setting/', ['uses' => 'UserController@setting', 'as' => 'app.user.setting']);
    Route::get('/user/transfer-period/', ['uses' => 'UserController@duration', 'as' => 'app.user.duration']);
    Route::post('/user/transfer-period/', ['uses' => 'UserController@post_duration', 'as' => 'app.user.duration']);
    Route::resource('/user', 'UserController', ['as' => 'app']);
    
    Route::resource('/notification', 'NotificationController', ['as' => 'app']);


    Route::get('/shipment/filter/{addressType?}/{shipmentStatus?}', ['uses' => 'ShipmentController@filter', 'as' => 'app.shipment.track']);
    Route::resource('/shipment', 'ShipmentController', ['as' => 'app']);
    Route::get('/shipment-track/', ['uses' => 'ShipmentController@get_track', 'as' => 'app.shipment.track']);
    Route::post('/shipment-track/', ['uses' => 'ShipmentController@post_track', 'as' => 'app.shipment.track']);

    Route::get('/order/confirm-order',  ['uses' => 'OrderController@get_confirm', 'as' => 'app.order.confirm']);
    Route::post('/order/confirm-order',  ['uses' => 'OrderController@post_confirm', 'as' => 'app.order.confirm']);
    Route::resource('/order', 'OrderController', ['as' => 'app']);

    Route::resource('/coupon', 'CouponController', ['as' => 'app']);
    Route::resource('/package', 'PackageController', ['as' => 'app']);
    Route::resource('/report', 'ReportController', ['as' => 'app']);
    Route::resource('/transfer', 'TransferController', ['as' => 'app']);
    Route::resource('/address', 'AddressController', ['as' => 'app']);
    Route::get('/address-list/{address_type}', ['uses' => 'AddressController@list_by_type', 'as' => 'app.address.list']);

    Route::resource('/bank', 'BankController', ['as' => 'app']);
});

app/Models/Shipment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;

class Shipment extends Model
{
    use SoftDeletes;

    protected $with = ['provider_schedule', 'status', 'services'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    protected $guarded = [];

    public function setDateAttribute($value)
    {
        $this->attributes['date'] = Carbon::parse($value)->format('d/m/Y');
    }

    public function getCreatedAtAttribute($value)
    {
        return \Carbon\Carbon::parse($value)->format('Y-m-d');
    }

    // public function getDateAttribute($value)
    // {
    //     return \Carbon\Carbon::parse($value)->format('Y-m-d');
    // }
    
    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    // get the last status onl to show as main one.
    public function status()
    {
        return $this->hasOne('App\Models\ShipmentStatus')->latest();
    }

    public function statuses()
    {
        return $this->hasMany('App\Models\ShipmentStatus');
    }

    public function order()
    {
        return $this->belongsTo('App\Models\Order', 'order_id');
    }

    public function money_receiver()
    {
        return $this->belongsTo('App\Models\ShipmentMoneyReceiver', 'shipment_money_receiver_id');
    }

    public function provider_schedule()
    {
        return $this->belongsTo('App\Models\ShipmentProviderSchedule', 'shipment_provider_schedule_id');
    }

    public function receiver()
    {
        return $this->belongsTo('App\Models\Address', 'receiver_address');
    }

    public function sender()
    {
        return $this->belongsTo('App\Models\Address', 'sender_address');
    }

    public function services()
    {
        return $this->belongsToMany('App\Models\ShipmentService', 'shipments_services', 'shipment_id', 'shipment_services_id');
    }

    public function method()
    {
        return $this->belongsTo('App\Models\ShipmentMethod', 'shipment_method_id');
    }

    public function getTotalPrice()
    {
        $total = 0;
        $totalWithoutItemCost = 0;

        foreach($this->services as $service)
        {
            $total += $service->cost;
            $totalWithoutItemCost += $service->cost;
        }

        if(! is_null($this->item_cost) && $this->shipment_method_id == 1)
        {
            $total += $this->item_cost;
            $total += \App\Models\AppSetting::first()->delivery_cost;
            return $total;

        }
        else if(is_null($this->item_cost) && $this->shipment_method_id == 2)
        {
            $totalWithoutItemCost += \App\Models\AppSetting::first()->delivery_cost;
            return $totalWithoutItemCost;
        }
    }
}

app/Http/Controllers/Admin/ShipmentScheduleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\ShipmentProvider;
use App\Models\ShipmentProviderSchedule;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Shipment;

class ShipmentScheduleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $schedules = ShipmentProviderSchedule::orderBy('id', 'desc')->get();

        return view('admin.shipment_schedule.index', compact('schedules'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $providers = ShipmentProvider::pluck('name', 'id');

        return view('admin.shipment_schedule.create', compact('providers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // return $request->all();
        // $this->validate($request, 
        //     ['email' => 'email|unique:users']
        // );

        $schedule = ShipmentProviderSchedule::create($request->except('days'));
        $schedule->days()->attach($request->days);
        return redirect(route('admin.shipment-schedule.index'))->with('message', 'تم حفظ المعلومات بنجاح!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Shipment  $shipment
     * @return \Illuminate\Http\Response
     */
    public function show(Shipment $shipment)
    {
        // return view('admin.shipment.show', compact('shipment'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Shipment  $shipment
     * @return \Illuminate\Http\Response
     */
    public function edit(ShipmentProviderSchedule $schedule)
    {
        $providers = ShipmentProvider::pluck('name', 'id');

        return view('admin.shipment_schedule.edit', compact('schedule', 'providers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Shipment  $shipment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ShipmentProviderSchedule $schedule)
    {
        $schedule->update($request->except('days'));
        $schedule->days()->sync($request->days);

        return redirect(route('admin.shipment-schedule.index'))->with('message', 'تم حفظ المعلومات بنجاح!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Shipment  $shipment
     * @return \Illuminate\Http\Response
     */
    public function destroy(ShipmentProviderSchedule $schedule)
    {
        return redirect(route('admin.shipment-schedule.index'))->with('message', 'بإمكانك تعطيل هذا الوقت ﻷنه مرتبط بطلبات مسبقة.');
        $schedule->delete();
        $schedule->days()->detach();

        return redirect(route('admin.shipment-schedule.index'))->with('message', 'تم حذف المعلومات بنجاح!');
    }
}

resources/views/admin/shipment_schedule/create.blade.php
@extends('layouts.admin')
@section('title')
إضافة خيار توصيل جديد
@endsection
@section('content')
<div class="m-portlet">
	<div class="m-portlet__body">
        {!! Form::open(['route' => 'admin.shipment-schedule.store']) !!}
            <div class="form-group m-form__group">
                <label>الحالة*</label>
                {!! Form::select('enable', ['غير مفعل','مفعل'], 1 , ['class' => 'form-control m-select2 m-input m-input--solid']) !!}
            </div>
            <div class="form-group m-form__group">
                <label>مزود الخدمة*</label>
                {!! Form::select('shipment_provider_id', $providers, null, ['class' => 'form-control m-select2 m-input m-input--solid', 'id' => 'm_select2_1_modal']) !!}
            </div>
            <div class="form-group m-form__group">
                <label>اﻷيام*</label>
                {!! Form::select('days[]', \DB::table('days')->pluck('name', 'id'), null, ['class' => 'form-control m-select2 m-input m-input--solid', 'id' => 'm_select2_3', 'multiple' => 'multiple']) !!}
            </div>
            <div class="form-group m-form__group">
                <label>الوقت من*</label>
                {!! Form::text('from', null, ['class' => 'form-control m-input m-input--solid', 'id' => 'm_timepicker_1', 'readonly']) !!}
            </div>
            <div class="form-group m-form__group">
                <label>الوقت إلى*</label>
                {!! Form::text('to', null, ['class' => 'form-control m-input m-input--solid', 'id' => 'm_timepicker_1', 'readonly']) !!}
            </div>
            <div class="col-md-12 text-center">
                <button type="submit" class="btn btn-primary btn-sm m-btn m-btn--icon m-btn--wide">
                    <span>
                        <i class="la la-save"></i>
                        <span>حفظ</span>
                    </span>
                </button>
            </div>
        {!! Form::close() !!}
	</div>
</div>

@endsection

@section('script')
<script src="/assets/admin/demo/default/custom/crud/forms/widgets/select2.js" type="text/javascript"></script>
<script src="/assets/admin/demo/default/custom/crud/forms/widgets/bootstrap-timepicker.js" type="text/javascript"></script>
@endsection

resources/views/admin/shipment_schedule/edit.blade.php
@extends('layouts.admin')
@section('title')
تعديل خيار توصيل
@endsection
@section('content')
<div class="m-portlet">
	<div class="m-portlet__body">
        {!! Form::model($schedule, ['route' => ['admin.shipment-schedule.update', $schedule]]) !!}
        {{ method_field('PATCH') }}
            <div class="form-group m-form__group">
                <label>الحالة*</label>
                {!! Form::select('enable', ['غير مفعل','مفعل'], 1 , ['class' => 'form-control m-select2 m-input m-input--solid']) !!}
            </div>
            <div class="form-group m-form__group">
                <label>مزود الخدمة*</label>
                {!! Form::select('shipment_provider_id', $providers, null, ['class' => 'form-control m-select2 m-input m-input--solid', 'id' => 'm_select2_1_modal']) !!}
            </div>
            <div class="form-group m-form__group">
                <label>اﻷيام*</label>
                {!! Form::select('days[]', \DB::table('days')->pluck('name', 'id'), null, ['class' => 'form-control m-select2 m-input m-input--solid', 'id' => 'm_select2_3', 'multiple' => 'multiple']) !!}
            </div>
            <div class="form-group m-form__group">
                <label>الوقت من*</label>
                {!! Form::text('from', null, ['class' => 'form-control m-input m-input--solid', 'id' => 'm_timepicker_1', 'readonly']) !!}
            </div>
            <div class="form-group m-form__group">
                <label>الوقت إلى*</label>
                {!! Form::text('to', null, ['class' => 'form-control m-input m-input--solid', 'id' => 'm_timepicker_1', 'readonly']) !!}
            </div>
            <div class="col-md-12 text-center">
                <button type="submit" class="btn btn-primary btn-sm m-btn m-btn--icon m-btn--wide">
                    <span>
                        <i class="la la-save"></i>
                        <span>حفظ</span>
                    </span>
                </button>
            </div>
        {!! Form::close() !!}
	</div>
</div>

@endsection

@section('script')
<script src="/assets/admin/demo/default/custom/crud/forms/widgets/select2.js" type="text/javascript"></script>
<script src="/assets/admin/demo/default/custom/crud/forms/widgets/bootstrap-timepicker.js" type="text/javascript"></script>
@endsection

resources/views/admin/shipment_schedule/index.blade.php
@extends('layouts.admin')
@section('title')
عرض أوقات وأسعار الشحن
@endsection
@section('content')
<div class="m-portlet">
	<div class="m-portlet__body">
        <div class="row">
            <div class="col-md-12 text-center">
                <a href="{{ route('admin.shipment-schedule.create') }}" class="btn btn-primary btn-sm m-btn m-btn--icon m-btn--wide">
                    <span>
                        <i class="flaticon-plus"></i>
                        <span>إضافة جديد</span>
                    </span>
                </a>
            </div>
        </div>
        <br>
        <div class="m-input-icon m-input-icon--left">
            <input type="text" class="form-control m-input" placeholder="البحث في الجدول ..." id="generalSearch">
            <span class="m-input-icon__icon m-input-icon__icon--left">
                <span><i class="la la-search"></i></span>
            </span>
        </div>
        <br>
        <table class="m-datatable" width="100%">
            <thead>
                <tr>
                    <th title="Field #1" data-field="اﻷيام">اﻷيام</th>
                    <th title="Field #2" data-field="الوقت من">الوقت من</th>
                    <th title="Field #3" data-field="الوقت إلى">الوقت إلى</th>
                    <th title="Field #6" data-field="الحالة">الحالة</th>
                    <th title="Field #7" data-field="مزود الخدمة">مزود الخدمة</th>
                    <th title="Field #8" data-field="أدوات التحكم">أدوات التحكم</th>
                </tr>
            </thead>
            <tbody>
                @foreach($schedules as $schedule)
                <tr>
                    <td>
                    @foreach($schedule->days as $day)
                    {{ $day->name }}, 
                    @endforeach
                    </td>
                    <td>{{ $schedule->from }}</td>
                    <td>{{ $schedule->to }}</td>
                    <td>{{ $schedule->enable() }}</td>
                    <td>{{ $schedule->provider->name }}</td>
                    <td>
                        <a href="{{ route('admin.shipment-schedule.edit', $schedule) }}" class="btn btn-warning m-btn m-btn--icon btn-sm m-btn--icon-only">
                            <i class="flaticon-edit"></i>
                        </a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
	</div>
</div>
@endsection

resources/views/admin/shipment_schedule/show.blade.php
@extends('layouts.admin')
@section('title')
عرض الشحنة لرقم التتبع {{ $shipment->tracking_number }}
@endsection
@section('content')
<div class="m-portlet m-portlet--mobile m-portlet--body-progress-">
	<div class="m-portlet__head">
		<div class="m-portlet__head-caption">
			<div class="m-portlet__head-title">
				<h3 class="m-portlet__head-text">
					حالة الشحن
				</h3>
			</div>			
		</div>
	</div>
	<div class="m-portlet__body">
		<table class="table m-table m-table--head-bg-brand">
			<thead class="thead-inverse">
				<tr>
					<th>#</th>
					<th>حالة الشحن</th>
				</tr>
			</thead>
			<tbody>
				@php $i = 1 @endphp
				@foreach($shipment->statuses as $status)
				<tr>
					<th>{{ $i++ }}</th>
					<td>
						<strong>{{ $status->name }}</strong>
						@if($status->statuses()->count() > 0)
						<div class="m-section__content">
							<div class="m-list-timeline">
								<div class="m-list-timeline__items">
									@foreach($status->statuses as $extraStatus)
										<div class="m-list-timeline__item">
											<span class="m-list-timeline__badge m-list-timeline__badge--success"></span>
											<span class="m-list-timeline__text">{{ $extraStatus->name }}</span>
											<span class="m-list-timeline__time">{{ $extraStatus->created_at }}</span>
										</div>
									@endforeach
								</div>
							</div>
						</div>
						@endif
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>
</div>

@endsection