routes/web.php
<?php

// guest routes
Auth::routes(['verify' => true]);

Route::get('/register/', ['uses' => '\App\Http\Controllers\Auth\RegisterController@showRegistrationForm']);
Route::get('/register/{role}', ['uses' => '\App\Http\Controllers\Auth\RegisterController@index']);
Route::post('/register/{role}', ['uses' => '\App\Http\Controllers\Auth\RegisterController@register']);

Route::group(['namespace' => 'App'], function () {
    Route::get('/', ['uses' => 'HomeController@index', 'as' => 'app.home.index']);
    Route::get('/contact-us', ['uses' => 'HomeController@contact', 'as' => 'app.home.contact']);
    Route::get('/about', ['uses' => 'HomeController@about', 'as' => 'app.home.about']);
    Route::get('/terms', ['uses' => 'HomeController@term', 'as' => 'app.home.term']);
    Route::get('/privacy', ['uses' => 'HomeController@privacy', 'as' => 'app.home.privacy']);
});

Route::group(['middleware' => ['role:admin'], 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'admin.dashboard.index']);
    Route::post('/user/list', ['uses' => 'UserController@list', 'as' => 'admin']);
    Route::resource('/user', 'UserController', ['as' => 'admin']);
    Route::get('/user/{user}/orders', ['uses' => 'UserController@orders', 'as' => 'admin.user.order']);
    Route::get('/user/{user}/balance', ['uses' => 'UserController@balances', 'as' => 'admin.user.balance']);
    Route::get('/user/{user}/shipment', ['uses' => 'UserController@shipments', 'as' => 'admin.user.shipment']);
    Route::get('/user/{user}/address', ['uses' => 'UserController@addresses', 'as' => 'admin.user.address']);

    Route::resource('/order', 'OrderController', ['as' => 'admin']);
    Route::post('/order/getOrdersByUser', ['uses' => 'OrderController@getOrdersByUser', 'as' => 'admin.order.user']);
    Route::resource('/shipment', 'ShipmentController', ['as' => 'admin']);
    Route::resource('/shipment.status', 'ShipmentStatusController', ['as' => 'admin']);
    Route::resource('/shipment.service', 'ShipmentServiceController', ['as' => 'admin']);
    Route::resource('/shipment-schedule', 'ShipmentScheduleController', ['as' => 'admin']);
    Route::resource('/shipment-provider', 'ShipmentProviderController', ['as' => 'admin']);

    Route::resource('/bank', 'BankController', ['as' => 'admin']);
    Route::post('/bank/getOrdersByUser', ['uses' => 'BankController@getBanksByUser', 'as' => 'admin.bank.user']);

    Route::resource('/bank-type', 'BankTypeController', ['as' => 'admin']);
    Route::resource('/coupon', 'CouponController', ['as' => 'admin']);
    Route::resource('/package', 'PackageController', ['as' => 'admin']);
    Route::resource('/report', 'ReportController', ['as' => 'admin']);
    Route::resource('/transfer', 'TransferController', ['as' => 'admin']);
    Route::resource('/address', 'AddressController', ['as' => 'admin']);
    Route::resource('/app-setting', 'AppSettingController', ['as' => 'admin']);
    Route::resource('/slider', 'SliderController', ['as' => 'admin']);
});

Route::group(['namespace' => 'App', 'middleware' => ['role:admin|trader|customer', 'verified', 'packageIsSelected']], function () {
    Route::get('/user/setting/', ['uses' => 'UserController@setting', 'as' => 'app.user.setting']);
    Route::get('/user/transfer-period/', ['uses' => 'UserController@duration', 'as' => 'app.user.duration']);
    Route::post('/user/transfer-period/', ['uses' => 'UserController@post_duration', 'as' => 'app.user.duration']);
    Route::resource('/user', 'UserController', ['as' => 'app']);
    
    Route::resource('/notification', 'NotificationController', ['as' => 'app']);


    Route::get('/shipment/filter/{addressType?}/{shipmentStatus?}', ['uses' => 'ShipmentController@filter', 'as' => 'app.shipment.track']);
    Route::resource('/shipment', 'ShipmentController', ['as' => 'app']);
    Route::get('/shipment-track/', ['uses' => 'ShipmentController@get_track', 'as' => 'app.shipment.track']);
    Route::post('/shipment-track/', ['uses' => 'ShipmentController@post_track', 'as' => 'app.shipment.track']);

    Route::get('/order/confirm-order',  ['uses' => 'OrderController@get_confirm', 'as' => 'app.order.confirm']);
    Route::post('/order/confirm-order',  ['uses' => 'OrderController@post_confirm', 'as' => 'app.order.confirm']);
    Route::resource('/order', 'OrderController', ['as' => 'app']);

    Route::resource('/coupon', 'CouponController', ['as' => 'app']);
    Route::resource('/package', 'PackageController', ['as' => 'app']);
    Route::resource('/report', 'ReportController', ['as' => 'app']);
    Route::resource('/transfer', 'TransferController', ['as' => 'app']);
    Route::resource('/address', 'AddressController', ['as' => 'app']);
    Route::get('/address-list/{address_type}', ['uses' => 'AddressController@list_by_type', 'as' => 'app.address.list']);

    Route::resource('/bank', 'BankController', ['as' => 'app']);
});

app/Models/Shipment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;

class Shipment extends Model
{
    use SoftDeletes;

    protected $with = ['provider_schedule', 'status', 'services'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    protected $guarded = [];

    public function setDateAttribute($value)
    {
        $this->attributes['date'] = Carbon::parse($value)->format('d/m/Y');
    }

    public function getCreatedAtAttribute($value)
    {
        return \Carbon\Carbon::parse($value)->format('Y-m-d');
    }

    // public function getDateAttribute($value)
    // {
    //     return \Carbon\Carbon::parse($value)->format('Y-m-d');
    // }
    
    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    // get the last status onl to show as main one.
    public function status()
    {
        return $this->hasOne('App\Models\ShipmentStatus')->latest();
    }

    public function statuses()
    {
        return $this->hasMany('App\Models\ShipmentStatus');
    }

    public function order()
    {
        return $this->belongsTo('App\Models\Order', 'order_id');
    }

    public function money_receiver()
    {
        return $this->belongsTo('App\Models\ShipmentMoneyReceiver', 'shipment_money_receiver_id');
    }

    public function provider_schedule()
    {
        return $this->belongsTo('App\Models\ShipmentProviderSchedule', 'shipment_provider_schedule_id');
    }

    public function receiver()
    {
        return $this->belongsTo('App\Models\Address', 'receiver_address');
    }

    public function sender()
    {
        return $this->belongsTo('App\Models\Address', 'sender_address');
    }

    public function services()
    {
        return $this->belongsToMany('App\Models\ShipmentService', 'shipments_services', 'shipment_id', 'shipment_services_id');
    }

    public function method()
    {
        return $this->belongsTo('App\Models\ShipmentMethod', 'shipment_method_id');
    }

    public function getTotalPrice()
    {
        $total = 0;
        $totalWithoutItemCost = 0;

        foreach($this->services as $service)
        {
            $total += $service->cost;
            $totalWithoutItemCost += $service->cost;
        }

        if(! is_null($this->item_cost) && $this->shipment_method_id == 1)
        {
            $total += $this->item_cost;
            $total += \App\Models\AppSetting::first()->delivery_cost;
            return $total;

        }
        else if(is_null($this->item_cost) && $this->shipment_method_id == 2)
        {
            $totalWithoutItemCost += \App\Models\AppSetting::first()->delivery_cost;
            return $totalWithoutItemCost;
        }
    }
}

app/User.php
<?php

namespace App;

class User extends Models\User {
    //leave this empty
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use App\Models\Order;
use App\Models\Package;
use Spatie\Permission\Models\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    public function list()
    {
        $users = User::latest()->get();

        return response()->json(['data' => $users]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::latest()->paginate(15);

        return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::pluck('display_name', 'id');
        $packages = Package::pluck('name', 'id');

        return view('admin.user.create', compact('roles', 'packages'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, 
            ['email' => 'email|unique:users']
        );

        $user = User::create($request->except(['role_id']));
        $user->update(['policies' => \App\Models\Package::find($request->package_id)->policy_number]);
        
        $user->assignRole($request->role_id);
        
        return redirect(route('admin.user.index'))->with('message', 'تم حفظ المعلومات بنجاح!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $pendingOrders = Order::where('user_id', $user->id)->whereIn('order_status_id', [1,2])->count();
        $pendingTransfer = \App\Models\Balance::where('user_id', $user->id)->first()->balance;

        return view('admin.user.show', compact('user', 'pendingOrders','pendingTransfer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::pluck('display_name', 'id');
        $packages = Package::pluck('name', 'id');

        return view('admin.user.edit', compact('user', 'roles', 'packages'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, 
            ['email' => 'email|unique:users,email,'.$user->id]
        );

        $user->update($request->except(['role_id', 'password']));

        if(! is_null($user->password))
        {
            $user->password = bcrypt($request->password);
            $user->save();
        }

        if($request->email_verified_at == 0)
        {
            $user->email_verified_at = \Carbon\Carbon::now();
            $user->save();
        }
        else if($request->email_verified_at == 1)
        {
            $user->email_verified_at = null;
            $user->save();
        }
        
        $user->syncRoles($request->role_id);
        
        return redirect(route('admin.user.index'))->with('message', 'تم حفظ المعلومات بنجاح!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        
        return redirect(route('admin.user.index'))->with('message', 'تم حذف المعلومات بنجاح!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function orders(User $user)
    {
        return view('admin.user.order', compact('user'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function addresses(User $user)
    {
        return view('admin.user.address', compact('user'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function shipments(User $user)
    {
        return view('admin.user.shipment', compact('user'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function balances(User $user)
    {
        // قيمة بضاعة لم تسلم
        $pendingOrders = \App\Models\Shipment::whereHas('order', function($query) use ($user){
            return $query->whereIn('order_status_id', [1,2])->where('user_id', $user->id);
        })->get()->sum('item_cost');

        // مبالغ في انتظار التحويل
        $pendingTransfer = \App\Models\Balance::where('user_id', $user->id)->first()->balance;

        return view('admin.user.balance', compact('user', 'pendingOrders', 'pendingTransfer'));
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\User;
use Spatie\Permission\Models\Role;
use App\Models\TransferDuration;
use App\Models\Package;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $users = User::orderBy('id', 'desc')->get();

        // return view('app.user.show', auth()->user(), compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $roles = Role::pluck('display_name', 'id');

        // return view('app.user.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, 
            ['email' => 'email|unique:users']
        );

        $user = User::create($request->except(['role_id']));
        
        $user->assignRole($request->role_id);
        
        return redirect(route('app.user.show', auth()->user()))->with('message', 'تم حفظ المعلومات بنجاح!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('app.user.show', auth()->user(), compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::pluck('display_name', 'id');

        return view('app.user.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, 
            ['email' => 'email|unique:users,email,'.$user->id]
        );

        $user->update($request->except(['password']));

        if(! is_null($request->password))
        {
            $user->password = bcrypt($request->password);
            $user->save();
        }
        
        return redirect(route('app.user.show', auth()->user()))->with('message', 'تم حفظ المعلومات بنجاح!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        
        return redirect(route('app.user.show', auth()->user()))->with('message', 'تم حذف المعلومات بنجاح!');
    }

    public function duration()
    {
        $durations = TransferDuration::pluck('name', 'id');

        return view('app.transfer.duration', compact('durations'));
    }

    public function post_duration(Request $request)
    {
        $duration = TransferDuration::findOrFail($request->transfer_duration_id);
        auth()->user()->update(['transfer_duration_id' => $duration->id]);

        return redirect(route('app.user.show', auth()->user(), auth()->user()))->with('message', 'تم تحديث بياناتك بنجاح!');
    }

    public function setting()
    {
        $user = auth()->user();
        $packages = Package::pluck('name', 'id');

        return view('app.user.setting', compact('user', 'packages'));
    }
}

resources/views/admin/user/index.blade.php
@extends('layouts.admin')
@section('title')
عرض المستخدمين
@endsection
@section('content')
<div class="m-portlet">
	<div class="m-portlet__body">
        <div class="row">
            <div class="col-md-12 text-center">
                <a href="{{ route('admin.user.create') }}" class="btn btn-primary btn-sm m-btn m-btn--icon m-btn--wide">
                    <span>
                        <i class="flaticon-plus"></i>
                        <span>إضافة جديد</span>
                    </span>
                </a>
            </div>
        </div>
        <br>
        <div class="m-input-icon m-input-icon--left">
            <input type="text" class="form-control m-input" placeholder="البحث في الجدول ..." id="generalSearch">
            <span class="m-input-icon__icon m-input-icon__icon--left">
                <span><i class="la la-search"></i></span>
            </span>
        </div>
        <br>
        <table class="m-datatable" width="100%">
            <thead>
                <tr>
                    <th title="Field #1" data-field="رقم المستخدم">#</th>
                    <th title="Field #2" data-field="اﻹسم">اﻹسم</th>
                    <th title="Field #3" data-field="البريد اﻹلكتروني">البريد اﻹلكتروني</th>
                    <th title="Field #4" data-field="نوع المستخدم">نوع المستخدم</th>
                    <th title="Field #5" data-field="الرصيد">الرصيد</th>
                    <th title="Field #6" data-field="المزيد">أدوات التحكم</th>
                </tr>
            </thead>
            <tbody>
                @foreach($users as $user)
                <tr>
                    <td>#{{ $user->id }}</td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ implode(', ', $user->getRoleNames()->toArray()) }}</td>
                    <td>{{ ($user->balance) ? $user->balance->balance .' ريال سعودي' : '-' }} </td>
                    <td>
                        <a href="{{ route('admin.user.show', $user) }}" class="btn btn-info m-btn m-btn--icon btn-sm m-btn--icon-only">
                            <i class="flaticon-medical"></i>
                        </a>
                        <a href="{{ route('admin.user.edit', $user) }}" class="btn btn-warning m-btn m-btn--icon btn-sm m-btn--icon-only">
                            <i class="flaticon-edit"></i>
                        </a>
                        <form method="POST" action="{{ route('admin.user.destroy', $user) }}" style="display:none" id="removeForm">
                            <input type="submit" />
                            {{ method_field('DELETE') }}
                            {!! csrf_field() !!}
                        </form>
                        <a id="m_sweetalert_demo_9" onclick="javascript:document.getElementById('removeForm').submit();" href="#" class="btn btn-danger m-btn m-btn--icon btn-sm m-btn--icon-only">
                            <i class="flaticon-circle"></i>
                        </a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
	</div>
</div>
@endsection

@section('script')
<script src="/assets/admin/demo/default/custom/components/base/sweetalert2.js" type="text/javascript"></script>
@endsection

resources/views/admin/user/order.blade.php
@extends('layouts.admin')
@section('title')
عرض طلبات {{ $user->name }}
@endsection
@section('content')
<div class="row">
	<div class="col-xl-3 col-lg-4">
		<div class="m-portlet m-portlet--full-height  ">
			<div class="m-portlet__body">
				<div class="m-card-profile">
					<div class="m-card-profile__title m--hide">
						Your Profile
					</div>
					<div class="m-card-profile__pic">
						<div class="m-card-profile__pic-wrapper">	
							<img src="{{ $user->avatar() }}" alt="">
						</div>
					</div>
					<div class="m-card-profile__details">
						<span class="m-card-profile__name">{{ $user->name }}</span>
						<a href="" class="m-card-profile__email m-link">{{ $user->email }}</a>
					</div>
				</div>	
				<ul class="m-nav m-nav--hover-bg m-portlet-fit--sides">
					<li class="m-nav__separator m-nav__separator--fit"></li>
					<li class="m-nav__section m--hide">
						<span class="m-nav__section-text">القسم</span>
					</li>
					<li class="m-nav__item">
						<a href="{{ route('admin.user.show', $user) }}" class="m-nav__link">
							<i class="m-nav__link-icon flaticon-profile-1"></i>
							<span class="m-nav__link-title">  
								<span class="m-nav__link-wrap">      
									<span class="m-nav__link-text">معلومات المستخدم</span>      
								</span>
							</span>
						</a>
					</li>
					<li class="m-nav__item">
						<a href="{{ route('admin.user.order', $user) }}" class="m-nav__link">
						<i class="m-nav__link-icon flaticon-share"></i>
							<span class="m-nav__link-text">الطلبات</span>
						</a>
					</li>
					<li class="m-nav__item">
						<a href="{{ route('admin.user.shipment', $user) }}" class="m-nav__link">
							<i class="m-nav__link-icon flaticon-chat-1"></i>
							<span class="m-nav__link-text">الشحن</span>
						</a>
					</li>
					<li class="m-nav__item">
						<a href="{{ route('admin.user.balance', $user) }}" class="m-nav__link">
							<i class="m-nav__link-icon flaticon-graphic-2"></i>
							<span class="m-nav__link-text">الرصيد</span>
						</a>
					</li>
					<li class="m-nav__item">
						<a href="{{ route('admin.user.address', $user) }}" class="m-nav__link">
							<i class="m-nav__link-icon flaticon-time-3"></i>
							<span class="m-nav__link-text">العناوين</span>
						</a>
					</li>
				</ul>

				<div class="m-portlet__body-separator"></div>

			</div>			
		</div>	
	</div>
	<div class="col-xl-9 col-lg-8">
		<div class="m-portlet m-portlet--full-height">
			<div class="m-portlet__body">
			<div class="m-input-icon m-input-icon--left">
				<input type="text" class="form-control m-input" placeholder="البحث في الجدول ..." id="generalSearch">
				<span class="m-input-icon__icon m-input-icon__icon--left">
					<span><i class="la la-search"></i></span>
				</span>
			</div>
			<br>
                <table class="m-datatable" width="100%">
                <thead>
                    <tr>
						<th>#رقم الطلب</th>
						<th>مقدم الطلب</th>
						<th>مستلم الطلب</th>
						<th>حالة الطلب</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($user->orders as $order)
                    <tr>
						<td><a href="{{ route('admin.order.show', $order) }}">#{{ $order->id }}</a></td>
						<td>{{ $order->user->name }}</td>
						<td>{{ $order->shipment->receiver->name }}</td>
						<td>{{ $order->status->name }}</td>
					</tr>
                    @endforeach
                </tbody>
            </table>
			</div>
			<!-- end m-portlet__body -->
		</div>
	</div>
</div>

@endsection

resources/views/admin/user/shipment.blade.php
@extends('layouts.admin')
@section('title')
عرض طلبات الشحن {{ $user->name }}
@endsection
@section('content')
<div class="row">
	<div class="col-xl-3 col-lg-4">
		<div class="m-portlet m-portlet--full-height  ">
			<div class="m-portlet__body">
				<div class="m-card-profile">
					<div class="m-card-profile__title m--hide">
						Your Profile
					</div>
					<div class="m-card-profile__pic">
						<div class="m-card-profile__pic-wrapper">	
							<img src="{{ $user->avatar() }}" alt="">
						</div>
					</div>
					<div class="m-card-profile__details">
						<span class="m-card-profile__name">{{ $user->name }}</span>
						<a href="" class="m-card-profile__email m-link">{{ $user->email }}</a>
					</div>
				</div>	
				<ul class="m-nav m-nav--hover-bg m-portlet-fit--sides">
					<li class="m-nav__separator m-nav__separator--fit"></li>
					<li class="m-nav__section m--hide">
						<span class="m-nav__section-text">القسم</span>
					</li>
					<li class="m-nav__item">
						<a href="{{ route('admin.user.show', $user) }}" class="m-nav__link">
							<i class="m-nav__link-icon flaticon-profile-1"></i>
							<span class="m-nav__link-title">  
								<span class="m-nav__link-wrap">      
									<span class="m-nav__link-text">معلومات المستخدم</span>      
								</span>
							</span>
						</a>
					</li>
					<li class="m-nav__item">
						<a href="{{ route('admin.user.order', $user) }}" class="m-nav__link">
						<i class="m-nav__link-icon flaticon-share"></i>
							<span class="m-nav__link-text">الطلبات</span>
						</a>
					</li>
					<li class="m-nav__item">
						<a href="{{ route('admin.user.shipment', $user) }}" class="m-nav__link">
							<i class="m-nav__link-icon flaticon-chat-1"></i>
							<span class="m-nav__link-text">الشحن</span>
						</a>
					</li>
					<li class="m-nav__item">
						<a href="{{ route('admin.user.balance', $user) }}" class="m-nav__link">
							<i class="m-nav__link-icon flaticon-graphic-2"></i>
							<span class="m-nav__link-text">الرصيد</span>
						</a>
					</li>
					<li class="m-nav__item">
						<a href="{{ route('admin.user.address', $user) }}" class="m-nav__link">
							<i class="m-nav__link-icon flaticon-time-3"></i>
							<span class="m-nav__link-text">العناوين</span>
						</a>
					</li>
				</ul>

				<div class="m-portlet__body-separator"></div>

			</div>			
		</div>	
	</div>
	<div class="col-xl-9 col-lg-8">
		<div class="m-portlet m-portlet--full-height">
			<div class="m-portlet__body">
			<div class="m-input-icon m-input-icon--left">
				<input type="text" class="form-control m-input" placeholder="البحث في الجدول ..." id="generalSearch">
				<span class="m-input-icon__icon m-input-icon__icon--left">
					<span><i class="la la-search"></i></span>
				</span>
			</div>
			<br>
				<table class="m-datatable" width="100%">
				<thead class="thead-inverse">
					<tr>
						<th title="Field #1" data-field="رقم التتبع">رقم التتبع</th>
						<th title="Field #2" data-field="رقم الطلب">رقم الطلب</th>
						<th title="Field #3" data-field="موعد اﻹستلام">موعد اﻹستلام</th>
						<th title="Field #4" data-field="حالة الشحن">حالة الشحن</th>
						<th title="Field #5" data-field="متحمل قيمة التوصيل">متحمل قيمة التوصيل</th>
					</tr>
				</thead>
				<tbody>
					@foreach($user->orders as $order)
					<tr>
						<td><a href="{{ route('admin.shipment.show', $order->shipment) }}">#{{ $order->shipment->tracking_number }}</a></td>
						<td><a href="{{ route('admin.order.show', $order->shipment->order) }}">#{{ $order->shipment->order->id }}</a></td>
						<td>{{ $order->shipment->date }} - ({{ $order->shipment->provider_schedule->from }} - {{ $order->shipment->provider_schedule->to }})</td>
						<td><a href="#" data-toggle="modal" data-target="#m_modal_{{ $order->shipment->id }}">أضغط للتفاصيل</a></td>
                    <!--begin::Modal-->
                    <div class="modal fade" id="m_modal_{{ $order->shipment->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">تفاصيل الشحن</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                        <div class="m-demo">
                            <div class="m-demo__preview">
                                <div class="m-list-timeline">
                                    <div class="m-list-timeline__items">
                                        @if($order->shipment->statuses()->count() == 0)
                                        <p>لا يوجد تفاصيل في الوقت الحالي.</p>
                                        @else
                                        @foreach($order->shipment->statuses as $status)
                                        <div class="m-list-timeline__item">
                                            <span class="m-list-timeline__badge m-list-timeline__badge--success"></span>
                                            <span class="m-list-timeline__text">{{ $status->name }}
                                                <br>
                                                @if(! is_null($status->description))
                                                <p>{{ $status->description }}</p>
                                                @endif
                                            </span>
                                            <span class="m-list-timeline__time">{{ $status->created_at->diffForHumans() }}</span>
                                        </div>
                                        @endforeach
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                        </div>
                        </div>
                    </div>
                    </div>
                    <!--end::Modal-->
						<td>{{ $order->shipment->money_receiver->name }}</td>
					</tr>
					@endforeach
				</tbody>
			</table>
			</div>
			<!-- end m-portlet__body -->
		</div>
	</div>
</div>

@endsection